// FIFA20.js
window.playersData = [
  {"Name":"Lionel Messi","Overall":94,"Playstyle":"A visionary creator who glides past defenders and dictates tempo with effortless precision."},
  {"Name":"Cristiano Ronaldo","Overall":93,"Playstyle":"A relentless athletic finisher who thrives on aerial dominance and explosive movement."},
  {"Name":"Kylian Mbappé","Overall":92,"Playstyle":"A rapid breakaway threat who punishes high lines with ruthless acceleration and sharp shooting."},
  {"Name":"Erling Haaland","Overall":92,"Playstyle":"A powerhouse striker who overwhelms defenders with size, speed, and direct, deadly finishing."},
  {"Name":"Kevin De Bruyne","Overall":92,"Playstyle":"A midfield architect who breaks teams open with surgical long passes and pinpoint crosses."},
  {"Name":"Neymar Jr.","Overall":90,"Playstyle":"A flair-driven dribbler who plays with creativity, deception, and quick improvisation in tight spaces."},
  {"Name":"Harry Kane","Overall":90,"Playstyle":"A complete forward known for deep playmaking, clinical finishing, and smart positional movement."},
  {"Name":"Mohamed Salah","Overall":89,"Playstyle":"A left-footed winger who slices inside at speed and thrives on quick one-twos and sharp finishing."},
  {"Name":"Virgil van Dijk","Overall":89,"Playstyle":"A composed defensive leader who controls space with elite positioning and physical dominance."},
  {"Name":"Robert Lewandowski","Overall":89,"Playstyle":"A clinical box striker who positions himself perfectly to convert even the smallest openings."},
  {"Name":"Jude Bellingham","Overall":88,"Playstyle":"A dynamic box-to-box force who blends technical poise with aggressive forward driving runs."},
  {"Name":"Rodri","Overall":88,"Playstyle":"A calm conductor who stabilizes midfield with crisp distribution and flawless positioning."},
  {"Name":"Vinícius Jr.","Overall":88,"Playstyle":"A pacey left-side dribbler who dismantles defenses with acceleration and unpredictable feints."},
  {"Name":"Bukayo Saka","Overall":87,"Playstyle":"A balanced wide attacker who links play smoothly and creates chances with controlled dribbling."},
  {"Name":"Phil Foden","Overall":87,"Playstyle":"A nimble technician who thrives in tight pockets and manipulates defenders with quick touches."},
  {"Name":"Pedri","Overall":87,"Playstyle":"A metronome midfielder who excels with subtle movement and intelligent short combinations."},
  {"Name":"Bruno Fernandes","Overall":87,"Playstyle":"A risk-taking creator who constantly searches for killer passes and late-run shooting angles."},
  {"Name":"Frenkie de Jong","Overall":87,"Playstyle":"A gliding ball-carrier who progresses play through calm dribbling and pressure resistance."},
  {"Name":"Heung-min Son","Overall":86,"Playstyle":"A fast two-footed forward who specializes in breakaway goals and sharp diagonal runs."},
  {"Name":"Rúben Dias","Overall":86,"Playstyle":"A rigid defensive anchor who thrives on anticipation and strong front-foot defending."},
  {"Name":"Luka Modrić","Overall":86,"Playstyle":"A veteran midfielder who dictates rhythm through elegance, balance, and precise passing."},
  {"Name":"Bernardo Silva","Overall":86,"Playstyle":"A tireless dribbler who uses clever angles and footwork to break structured defenses."},
  {"Name":"Theo Hernández","Overall":85,"Playstyle":"An explosive fullback who surges forward relentlessly and creates danger on the overlap."},
  {"Name":"Achraf Hakimi","Overall":85,"Playstyle":"A rapid wing-back who attacks wide spaces with speed and early, dangerous deliveries."},
  {"Name":"Martin Ødegaard","Overall":85,"Playstyle":"A silky creator who orchestrates attacks with soft touches and disguised passes."},
  {"Name":"Declan Rice","Overall":85,"Playstyle":"A defensive shield who dominates duels and transitions smoothly into forward play."},
  {"Name":"Khvicha Kvaratskhelia","Overall":85,"Playstyle":"A creative winger who combines unpredictable dribbling with daring direct runs."},
  {"Name":"Trent Alexander-Arnold","Overall":85,"Playstyle":"A deep-lying playmaker fullback with long-range passing that unlocks defenses."},
  {"Name":"Marcus Rashford","Overall":84,"Playstyle":"A wide forward who thrives when attacking space with powerful, straight-line pace."},
  {"Name":"Lautaro Martínez","Overall":84,"Playstyle":"A gritty striker who mixes aggressive pressing with sharp turns and quick finishes."},
  {"Name":"Antoine Griezmann","Overall":84,"Playstyle":"A clever support striker who operates between lines with intelligent off-ball movement."},
  {"Name":"Joshua Kimmich","Overall":84,"Playstyle":"An all-round organizer who reads the game brilliantly and distributes with accuracy."},
  {"Name":"Jamal Musiala","Overall":84,"Playstyle":"A slippery dribbler who shifts direction effortlessly and excels in chaotic spaces."},
  {"Name":"João Cancelo","Overall":83,"Playstyle":"A fluid fullback who drifts into midfield zones and uses flair to break shape."},
  {"Name":"Ousmane Dembélé","Overall":83,"Playstyle":"A two-footed winger who destabilizes defenses with unpredictable sprints and trickery."},
  {"Name":"Kai Havertz","Overall":83,"Playstyle":"A smooth, tall forward who times runs well and finishes calmly inside the box."},
  {"Name":"Álvaro Morata","Overall":83,"Playstyle":"A mobile striker who excels at link-up play and drifting wide to pull defenders."},
  {"Name":"Manuel Neuer","Overall":83,"Playstyle":"A sweeping goalkeeper who plays like an extra defender and controls space behind the line."},
  {"Name":"Jan Oblak","Overall":83,"Playstyle":"A reaction-shot specialist with strong positioning and commanding presence in the box."},
  {"Name":"Mike Maignan","Overall":83,"Playstyle":"An athletic goalkeeper who reads one-on-ones well and distributes confidently."},
  {"Name":"Yassine Bounou","Overall":82,"Playstyle":"A momentum goalkeeper who thrives in high-pressure moments and penalty situations."},
  {"Name":"Diogo Jota","Overall":82,"Playstyle":"A direct forward who presses aggressively and finishes sharply from tight spaces."},
  {"Name":"Federico Valverde","Overall":82,"Playstyle":"A high-energy midfielder who combines long sprints with powerful ball strikes."},
  {"Name":"Riyad Mahrez","Overall":82,"Playstyle":"A finesse winger who slows the game down to beat players with timing and technique."},
  {"Name":"Ilkay Gündogan","Overall":82,"Playstyle":"A clever midfielder who specializes in late box arrivals and calm finishing."},
  {"Name":"Sandro Tonali","Overall":81,"Playstyle":"A gritty midfielder who switches play with long diagonals and strong tackles."},
  {"Name":"Christopher Nkunku","Overall":81,"Playstyle":"A versatile attacker who drifts into pockets and creates overloads through speed."},
  {"Name":"Serge Gnabry","Overall":81,"Playstyle":"A powerful winger who bursts past defenders and shoots early from angles."},
  {"Name":"Nicolò Barella","Overall":81,"Playstyle":"A scrappy playmaker who transitions quickly and injects energy into midfield battles."},
  {"Name":"Darwin Núñez","Overall":81,"Playstyle":"A chaotic striker who stretches defenses with nonstop runs and raw physicality."},
  {"Name":"Raphaël Varane","Overall":81,"Playstyle":"A calm center-back who relies on smart positioning and controlled recovery speed."},
  {"Name":"Kalidou Koulibaly","Overall":80,"Playstyle":"A strong, imposing defender who excels in one-on-one physical duels."},
  {"Name":"David Alaba","Overall":80,"Playstyle":"A flexible defender who dribbles confidently and builds attacks from the back."},
  {"Name":"Ederson","Overall":80,"Playstyle":"A ball-playing goalkeeper who launches precision long passes into attacking zones."},
  {"Name":"Thibaut Courtois","Overall":80,"Playstyle":"A towering shot-stopper with exceptional reflexes in close-range situations."},
  {"Name":"Casemiro","Overall":80,"Playstyle":"A destroyer-type midfielder who protects the back line with aggressive challenges."},
  {"Name":"João Félix","Overall":80,"Playstyle":"A fluid second striker who combines light touches with subtle creativity."},
  {"Name":"Mason Mount","Overall":79,"Playstyle":"A high-work-rate midfielder who links transitions and presses relentlessly."},
  {"Name":"Reece James","Overall":79,"Playstyle":"A strong two-way fullback who balances defensive solidity with powerful crosses."},
  {"Name":"Kyle Walker","Overall":79,"Playstyle":"A rapid defender who recovers aggressively and locks down wide channels."},
  {"Name":"Andrew Robertson","Overall":79,"Playstyle":"A tenacious fullback who drives forward and delivers early crosses at pace."},
  {"Name":"Pau Torres","Overall":79,"Playstyle":"A composed defender who prefers clean interceptions over risky tackles."},
  {"Name":"Gavi","Overall":78,"Playstyle":"A fiery midfielder who plays with intensity, tight control, and fearless duels."},
  {"Name":"Dominik Szoboszlai","Overall":78,"Playstyle":"A long-range threat who strikes the ball cleanly and advances play through sharp carries."},
  {"Name":"Edin Džeko","Overall":78,"Playstyle":"A tall target man who links play and finishes calmly under pressure."},
  {"Name":"Wilfried Zaha","Overall":78,"Playstyle":"A physical dribbler who consistently isolates defenders and attacks one-on-one."},
  {"Name":"Jack Grealish","Overall":78,"Playstyle":"A possession specialist who slows the game to create fouls and find passing lanes."},
  {"Name":"Ángel Di María","Overall":78,"Playstyle":"A crafty winger with bending crosses and clever left-footed combinations."},
  {"Name":"Kingsley Coman","Overall":78,"Playstyle":"A fleet-footed winger who relies on pure speed and quick directional changes."},
  {"Name":"Toni Kroos","Overall":78,"Playstyle":"A control-oriented passer who dictates tempo with measured long and short deliveries."},
  {"Name":"Rapinha","Overall":78,"Playstyle":"A sharp wide attacker who cuts inside to shoot and fights relentlessly in duels."},
  {"Name":"Ismaïla Sarr","Overall":77,"Playstyle":"A pace-driven winger who pushes defenders back with direct, vertical runs."},
  {"Name":"Christian Pulisic","Overall":77,"Playstyle":"A quick dribbler who thrives in broken play and counterattacking moments."},
  {"Name":"Giovanni Reyna","Overall":77,"Playstyle":"A smooth attacking midfielder who picks out creative gaps with soft footwork."},
  {"Name":"Mykhailo Mudryk","Overall":77,"Playstyle":"A blisteringly fast winger who excels in open-field sprints and sudden cuts."},
  {"Name":"James Maddison","Overall":77,"Playstyle":"A set-piece specialist with sharp vision and a knack for finding half-spaces."},
  {"Name":"Evan Ferguson","Overall":76,"Playstyle":"A young, physical striker who holds defenders off and finishes with composure."},
  {"Name":"Josko Gvardiol","Overall":76,"Playstyle":"A strong ball-carrying defender who breaks lines through confident dribbling."},
  {"Name":"Sven Botman","Overall":76,"Playstyle":"A disciplined defender who prioritizes positioning and clean defensive structure."},
  {"Name":"Brenden Aaronson","Overall":75,"Playstyle":"A high-energy presser who disrupts buildup and drives play forward relentlessly."},
  {"Name":"Leroy Sané","Overall":82,"Playstyle":"A direct speed merchant who stretches defenses and cuts inside for finesse shots."},
  {"Name":"Gabriel Jesus","Overall":81,"Playstyle":"A versatile forward who presses intensely and creates space through movement."},
  {"Name":"Richarlison","Overall":80,"Playstyle":"A combative attacker who uses physicality and aerial prowess to unsettle defenders."},
  {"Name":"Marquinhos","Overall":86,"Playstyle":"An elegant ball-playing defender who organizes from the back with calm authority."},
  {"Name":"Jules Koundé","Overall":83,"Playstyle":"A quick, agile defender who excels in recovery situations and one-on-one duels."},
  {"Name":"William Saliba","Overall":82,"Playstyle":"A physically dominant center-back who wins aerial battles and reads danger early."},
  {"Name":"Eder Militão","Overall":82,"Playstyle":"An athletic defender who combines speed with aggressive positioning."},
  {"Name":"Alessandro Bastoni","Overall":81,"Playstyle":"A left-footed ball-playing defender who initiates attacks with progressive passes."},
  {"Name":"Matthijs de Ligt","Overall":82,"Playstyle":"A commanding presence who dominates in the air and leads defensive organization."},
  {"Name":"Ronald Araújo","Overall":82,"Playstyle":"A powerful defensive wall who thrives in physical confrontations and recovery runs."},
  {"Name":"Alisson Becker","Overall":88,"Playstyle":"A composed shot-stopper with exceptional footwork and calm distribution under pressure."},
  {"Name":"Marc-André ter Stegen","Overall":84,"Playstyle":"A reflex specialist who excels in one-on-one situations and plays out from the back."},
  {"Name":"Gianluigi Donnarumma","Overall":85,"Playstyle":"A towering presence with cat-like reflexes and dominance in high crosses."},
  {"Name":"Emiliano Martínez","Overall":84,"Playstyle":"A vocal leader who excels at reading attackers and thrives in penalty shootouts."},
  {"Name":"Aaron Ramsdale","Overall":79,"Playstyle":"An agile shot-stopper who distributes quickly and commands his penalty area."},
  {"Name":"Jordan Pickford","Overall":79,"Playstyle":"A reactive keeper with strong footwork and brave decision-making in one-on-ones."},
  {"Name":"Unai Simón","Overall":78,"Playstyle":"A calm distributor who plays with composure and positions himself intelligently."},
  {"Name":"Gregor Kobel","Overall":79,"Playstyle":"A modern sweeper-keeper who rushes off his line and distributes with confidence."},
  {"Name":"André Onana","Overall":79,"Playstyle":"A bold ball-playing keeper who takes risks to initiate attacks from deep."},
  {"Name":"Álex Remiro","Overall":78,"Playstyle":"A consistent shot-stopper who positions well and handles pressure calmly."},
  {"Name":"Fabián Ruiz","Overall":80,"Playstyle":"A technical midfielder who controls tempo with silky touches and forward passes."},
  {"Name":"Youri Tielemans","Overall":79,"Playstyle":"A versatile midfielder who strikes from distance and switches play effectively."},
  {"Name":"Franck Kessié","Overall":79,"Playstyle":"A box-to-box warrior who contributes defensively and arrives late in the box."},
  {"Name":"Aurélien Tchouaméni","Overall":83,"Playstyle":"A physical midfielder who breaks up play and progresses the ball with driving runs."},
  {"Name":"Eduardo Camavinga","Overall":82,"Playstyle":"A dynamic, versatile midfielder who reads the game maturely and covers ground rapidly."},
  {"Name":"Enzo Fernández","Overall":82,"Playstyle":"A composed deep-lying playmaker who dictates tempo and delivers precise long balls."},
  {"Name":"Alexis Mac Allister","Overall":80,"Playstyle":"A well-rounded midfielder who combines pressing with clever off-ball movement."},
  {"Name":"Moisés Caicedo","Overall":80,"Playstyle":"A tenacious ball-winner who shields the defense and drives forward powerfully."},
  {"Name":"Exequiel Palacios","Overall":77,"Playstyle":"A combative midfielder who disrupts opponents and recycles possession efficiently."},
  {"Name":"Matheus Cunha","Overall":79,"Playstyle":"A creative forward who drops deep to link play and finishes with flair."},
  {"Name":"Victor Osimhen","Overall":86,"Playstyle":"An explosive striker who uses pace and power to terrorize defensive lines."},
  {"Name":"Dusan Vlahović","Overall":83,"Playstyle":"A traditional number nine who holds up play and converts chances clinically."},
  {"Name":"Tammy Abraham","Overall":78,"Playstyle":"A mobile striker who uses his frame to shield the ball and finish decisively."},
  {"Name":"Gianluca Scamacca","Overall":78,"Playstyle":"A tall target forward who combines physicality with technical ability in the box."},
  {"Name":"Aleksandar Mitrović","Overall":78,"Playstyle":"A bullish striker who dominates aerially and bullies defenders into mistakes."},
  {"Name":"Patrik Schick","Overall":79,"Playstyle":"A clinical finisher who positions himself smartly and strikes cleanly from range."},
  {"Name":"Ivan Toney","Overall":79,"Playstyle":"A complete forward who excels at hold-up play and scores from all ranges."},
  {"Name":"Ollie Watkins","Overall":79,"Playstyle":"A pacey striker who runs the channels relentlessly and finishes with composure."},
  {"Name":"Callum Wilson","Overall":77,"Playstyle":"An instinctive poacher who anticipates loose balls and converts half-chances."},
  {"Name":"Jonathan David","Overall":80,"Playstyle":"A smart runner who exploits space between defenders and finishes with precision."},
  {"Name":"Victor Boniface","Overall":78,"Playstyle":"A physical presence who combines strength with clever movement in tight spaces."},
  {"Name":"Randal Kolo Muani","Overall":80,"Playstyle":"A versatile forward who stretches defenses with pace and creative off-ball runs."},
  {"Name":"Marcus Thuram","Overall":81,"Playstyle":"A powerful runner who uses his size to hold defenders off and finish from range."},
  {"Name":"Rafael Leão","Overall":84,"Playstyle":"A devastating winger who accelerates past defenders and cuts inside to shoot."},
  {"Name":"Luis Díaz","Overall":82,"Playstyle":"A tricky left-winger who dribbles relentlessly and creates chaos in wide areas."},
  {"Name":"Julián Álvarez","Overall":82,"Playstyle":"A tireless forward who presses high and finishes with technical precision."},
  {"Name":"Gonçalo Ramos","Overall":79,"Playstyle":"A clinical striker who positions himself perfectly and converts chances efficiently."},
  {"Name":"Lois Openda","Overall":79,"Playstyle":"A rapid forward who exploits defensive lapses with electric acceleration."},
  {"Name":"Benjamin Šeško","Overall":78,"Playstyle":"A towering striker who combines aerial threat with surprising technical skill."},
  {"Name":"Rasmus Højlund","Overall":79,"Playstyle":"A physical forward who holds the ball up and finishes powerfully in the box."},
  {"Name":"Joao Pedro","Overall":78,"Playstyle":"A versatile attacker who drifts across the front line and creates space intelligently."},
  {"Name":"Mohamed Kudus","Overall":80,"Playstyle":"An explosive dribbler who carries the ball at pace and shoots from distance."},
  {"Name":"Kaoru Mitoma","Overall":79,"Playstyle":"A low-center-of-gravity winger who glides past challenges with exceptional close control."},
  {"Name":"Takefusa Kubo","Overall":79,"Playstyle":"A technical winger who manipulates the ball in tight spaces and delivers precise crosses."},
  {"Name":"Cole Palmer","Overall":80,"Playstyle":"A composed playmaker who executes with precision and thrives in crucial moments."},
  {"Name":"Florian Wirtz","Overall":82,"Playstyle":"A prodigious talent who creates magic in pockets and finishes with both feet."},
  {"Name":"Xavi Simons","Overall":80,"Playstyle":"A dynamic attacking midfielder who drives forward and shoots from range."},
  {"Name":"Nicolás González","Overall":78,"Playstyle":"A hardworking winger who tracks back defensively and attacks with directness."},
  {"Name":"Moussa Diaby","Overall":80,"Playstyle":"A pacey winger who exploits space behind defenses and shoots early."},
  {"Name":"Dejan Kulusevski","Overall":80,"Playstyle":"A physical winger who uses his body to shield possession and create angles."},
  {"Name":"Gabriel Martinelli","Overall":81,"Playstyle":"An energetic left-winger who presses relentlessly and attacks the box at speed."},
  {"Name":"Cody Gakpo","Overall":80,"Playstyle":"A versatile forward who drifts centrally and finishes with either foot."},
  {"Name":"Nico Williams","Overall":80,"Playstyle":"An electric winger who terrorizes fullbacks with blistering pace and tight control."},
  {"Name":"Brennan Johnson","Overall":77,"Playstyle":"A direct winger who runs in behind and finishes clinically on the break."},
  {"Name":"Alejandro Garnacho","Overall":78,"Playstyle":"A fearless winger who takes defenders on with skill and youthful confidence."},
  {"Name":"Ansu Fati","Overall":78,"Playstyle":"A composed finisher who finds space intelligently and shoots with precision."},
  {"Name":"Ferran Torres","Overall":79,"Playstyle":"A versatile attacker who makes intelligent runs and finishes calmly."},
  {"Name":"Dani Olmo","Overall":82,"Playstyle":"A creative midfielder who operates between lines with technical elegance."},
  {"Name":"Marco Asensio","Overall":79,"Playstyle":"A left-footed technician who cuts inside and curls shots into the far corner."},
  {"Name":"Hakim Ziyech","Overall":78,"Playstyle":"A set-piece specialist with a wand of a left foot for crosses and free kicks."},
  {"Name":"Leandro Trossard","Overall":79,"Playstyle":"A clever inverted winger who finds pockets and finishes with composure."},
  {"Name":"Jarrod Bowen","Overall":78,"Playstyle":"A hard-working winger who delivers crosses and scores from cutting inside."},
  {"Name":"Anthony Gordon","Overall":77,"Playstyle":"A direct winger who uses pace and trickery to beat defenders consistently."},
  {"Name":"Eberechi Eze","Overall":78,"Playstyle":"A silky dribbler who glides past challenges and strikes from distance."},
  {"Name":"Michael Olise","Overall":79,"Playstyle":"A technical playmaker who delivers pinpoint crosses and scores spectacular goals."},
  {"Name":"Pedro Neto","Overall":78,"Playstyle":"A quick-footed winger who excels in transitions and one-on-one situations."},
  {"Name":"Jeremie Frimpong","Overall":79,"Playstyle":"An explosive wing-back who bombs forward and creates overloads with relentless energy."},
  {"Name":"Denzel Dumfries","Overall":78,"Playstyle":"A powerful wing-back who attacks with physicality and arrives late in the box."},
  {"Name":"Alphonso Davies","Overall":84,"Playstyle":"A lightning-fast fullback who dominates the left flank with recovery pace and overlaps."},
  {"Name":"Ben Chilwell","Overall":77,"Playstyle":"An attacking fullback who delivers dangerous crosses and overlaps consistently."},
  {"Name":"Nuno Mendes","Overall":78,"Playstyle":"A rapid fullback who recovers defensively and pushes high in attack."},
  {"Name":"Ferland Mendy","Overall":78,"Playstyle":"A defensive-minded fullback who uses pace to shut down wingers."},
  {"Name":"Luke Shaw","Overall":78,"Playstyle":"A composed fullback who progresses play calmly and delivers quality crosses."},
  {"Name":"Diogo Dalot","Overall":77,"Playstyle":"A two-way fullback who balances defensive duties with attacking forays."},
  {"Name":"Malo Gusto","Overall":76,"Playstyle":"A composed young fullback who reads the game well and overlaps intelligently."},
  {"Name":"Jurrien Timber","Overall":79,"Playstyle":"A versatile defender who plays centrally or wide with technical composure."},
  {"Name":"Pedro Porro","Overall":78,"Playstyle":"An attacking wing-back who delivers dangerous crosses and shoots from distance."},
  {"Name":"Tariq Lamptey","Overall":75,"Playstyle":"A pocket rocket fullback who uses explosive pace to overwhelm opponents."},
  {"Name":"Destiny Udogie","Overall":76,"Playstyle":"A dynamic fullback who drives forward with pace and overlaps relentlessly."},
  {"Name":"Yankuba Minteh","Overall":75,"Playstyle":"A rapid winger who stretches defenses with direct running and raw speed."},
  {"Name":"Jeremie Boga","Overall":76,"Playstyle":"A tricky winger who uses close control to beat defenders in tight spaces."},
  {"Name":"Nathan Aké","Overall":78,"Playstyle":"A calm defender who steps into midfield confidently and covers multiple positions."},
  {"Name":"Lisandro Martínez","Overall":81,"Playstyle":"A combative defender who wins duels aggressively despite his smaller frame."},
  {"Name":"Cristian Romero","Overall":82,"Playstyle":"A fierce defender who plays on the edge and dominates physical battles."},
  {"Name":"Micky van de Ven","Overall":78,"Playstyle":"A rapid center-back who uses recovery pace to sweep behind the defensive line."},
  {"Name":"Benoît Badiashile","Overall":77,"Playstyle":"A tall, athletic defender who wins aerial duels and steps out confidently."},
  {"Name":"Wesley Fofana","Overall":78,"Playstyle":"A quick defender who reads danger early and intercepts with anticipation."},
  {"Name":"Ibrahima Konaté","Overall":80,"Playstyle":"A physically imposing defender who dominates in the air and defends aggressively."},
  {"Name":"Dayot Upamecano","Overall":80,"Playstyle":"An athletic defender who combines pace with strength in defensive duels."},
  {"Name":"Lucas Hernández","Overall":79,"Playstyle":"A versatile defender who plays centrally or wide with composure and intelligence."},
  {"Name":"Benjamin Pavard","Overall":79,"Playstyle":"A disciplined defender who reads the game well and distributes accurately."},
  {"Name":"Antonio Rüdiger","Overall":84,"Playstyle":"An aggressive defender who steps into midfield and wins duels through intensity."},
  {"Name":"Kim Min-jae","Overall":82,"Playstyle":"A dominant center-back who combines pace with aerial prowess and leadership."},
  {"Name":"Nikola Milenković","Overall":77,"Playstyle":"A composed defender who positions himself smartly and wins headers consistently."},
  {"Name":"Piero Hincapié","Overall":76,"Playstyle":"A left-footed defender who steps out with the ball and defends with maturity."},
  {"Name":"Edmond Tapsoba","Overall":78,"Playstyle":"A quick defender who uses recovery pace and reads attacking movements well."},
  {"Name":"Evan Ndicka","Overall":78,"Playstyle":"A strong, ball-playing defender who progresses play from the back confidently."},
  {"Name":"Jean-Clair Todibo","Overall":78,"Playstyle":"An athletic defender who dominates physically and plays out from the back."}
];
